export default defineEventHandler(() => {
  return [
    {
      id: 15,
      audio: "/audio/chill/lofi-chillhop/lunar-breeze.mp3",
      title: "Lunar Breeze",
      artist: "Nujabes",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Lofi, Ambient, Chill",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:34",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 16,
      audio: "/audio/chill/lofi-chillhop/rainy-day.mp3",
      title: "Rainy Day",
      artist: "Tomppabeats",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Lofi, Chillhop, Mellow",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:29",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 17,
      audio: "/audio/chill/lofi-chillhop/cats-dreams.mp3",
      title: "Cat's Dreams",
      artist: "Idealism",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Calm, Cozy, Lofi, Dreams",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:21",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 18,
      audio: "/audio/chill/lofi-chillhop/photograph.mp3",
      title: "Photograph",
      artist: "Joji",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Mesmerizing, Instrumental",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:16",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 19,
      audio: "/audio/chill/lofi-chillhop/polar-lights.mp3",
      title: "Polar Lights",
      artist: "Jinsang",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Chill, Vibes, Lofi",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "01:58",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 20,
      audio: "/audio/chill/lofi-chillhop/snow.mp3",
      title: "Snow",
      artist: "Saib",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Snow, Instrumental",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:22",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 21,
      audio: "/audio/chill/lofi-chillhop/melt.mp3",
      title: "Melt",
      artist: "Kudasai",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Beautiful Lofi",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:32",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 22,
      audio: "/audio/chill/lofi-chillhop/aura.mp3",
      title: "Aura",
      artist: "Ezzy",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Cosmic Lofi",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:29",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 23,
      audio: "/audio/chill/lofi-chillhop/over-the-moon.mp3",
      title: "Over The Moon",
      artist: "sadtoi",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Chill, Lofi, Relaxation",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "02:18",
        isFavorite: Math.random() < 0.5,
      },
    },
    {
      id: 24,
      audio: "/audio/chill/lofi-chillhop/after-you.mp3",
      title: "After You",
      artist: "Sleepy Fish",
      artwork: "/images/chill.jpg",
      album: "Lofi ChillHop",
      original: {
        genre: "Relaxing, Chill, Ambient",
        plays: Math.floor(Math.random() * 999) + 1,
        duration: "03:12",
        isFavorite: Math.random() < 0.5,
      },
    },
  ];
});
